// This test file is generated by AI

import { describe, it, expect, vi, afterEach, beforeEach } from 'vitest';
import request from 'supertest';
import express from 'express';

describe('dogRoutes', () => {
  beforeEach(() => {
    vi.resetModules();
  });

  afterEach(() => {
    vi.restoreAllMocks();
    vi.clearAllMocks();
    vi.unmock('../controllers/dogController');
  });

  it('should return 200, success true and mocked image url for GET /api/dogs/random', async () => {
    vi.doMock('../controllers/dogController', () => ({
      getDogImage: async (_req: any, res: any) => {
        res.status(200).json({
          success: true,
          data: {
            imageUrl: 'https://mocked-dog-image.jpg',
            status: 'success'
          }
        });
      }
    }));

    const { default: dogRoutes } = await import('../routes/dogRoutes');

    const app = express();
    app.use(express.json());
    app.use('/api/dogs', dogRoutes);

    const response = await request(app).get('/api/dogs/random');

    expect(response.status).toBe(200);
    expect(response.body.success).toBe(true);
    expect(response.body.data.imageUrl).toContain('mocked-dog-image');
  });

  it('should return 500 and error for GET /api/dogs/random', async () => {
    vi.doMock('../controllers/dogController', () => ({
      getDogImage: async (_req: any, res: any) => {
        res.status(500).json({
          success: false,
          error: 'Failed to fetch dog image: Network error'
        });
      }
    }));

    const { default: dogRoutes } = await import('../routes/dogRoutes');

    const app = express();
    app.use(express.json());
    app.use('/api/dogs', dogRoutes);

    const response = await request(app).get('/api/dogs/random');

    expect(response.status).toBe(500);
    expect(response.body.error).toBe('Failed to fetch dog image: Network error');
  });
});